CREATE TABLE VACAS(
	ID_PLASTICO INTEGER(10) PRIMARY KEY NOT NULL,
	ID_METAL INTEGER(10) NOT NULL,
	NACIMIENTO DATE,
	ID_MADRE INTEGER(10),
    NOMBRE_PADRE VARCHAR(20),
    REGISTRO_PADRE INTEGER(10),
    ATENDIO_PARTO VARCHAR(20),
    HORA_PARTO TIME,
    TIPO_PARTO VARCHAR(20),
    CALIDAD_CALOSTRO INTEGER(10),
    PROTEINA FLOAT(10,10),
    OBSERVACIONES VARCHAR(50)
);

CREATE TABLE VACUNAS(
	ID_VACUNA INTEGER(10) PRIMARY KEY NOT NULL,
	ID_VACA INTEGER(10) NOT NULL,
	FECHA DATE,

	CONSTRAINT FK_IDVACA
  	FOREIGN KEY (ID_VACA)
  	REFERENCES VACAS(ID_PLASTICO)
);

CREATE TABLE TRATAMIENTOS(
	ID_TRAT INTEGER(10) PRIMARY KEY NOT NULL,
	ID_VACA INTEGER(10) NOT NULL,
	FECHA DATE,
    SIGNOS VARCHAR(10),
    DESCRIPCION VARCHAR(20),
    OBSERVACIONES VARCHAR(50),

	CONSTRAINT FK_IDVACA_T
  	FOREIGN KEY (ID_VACA)
  	REFERENCES VACAS(ID_PLASTICO)
);

CREATE TABLE DESPARACITACION(
	ID_DESP INTEGER(10) PRIMARY KEY NOT NULL,
	ID_VACA INTEGER(10) NOT NULL,
	FECHA DATE,
    PESO FLOAT(10,10),

	CONSTRAINT FK_IDVACA_D
  	FOREIGN KEY (ID_VACA)
  	REFERENCES VACAS(ID_PLASTICO)
);

CREATE TABLE REPRODUCCION(
	ID_REP INTEGER(10) PRIMARY KEY NOT NULL,
	ID_VACA INTEGER(10) NOT NULL,
	NOMBRE_TORO VARCHAR(20),
    REGISTRO_TORO INTEGER(10),
    NUM_SERV INTEGER(10),
    TEC INTEGER(5),
    OBSERVACIONES VARCHAR(50),

	CONSTRAINT FK_IDVACA_R
  	FOREIGN KEY (ID_VACA)
  	REFERENCES VACAS(ID_PLASTICO)
);